---
- hosts: "{{ serverGroups }}"
  become: yes
  
  tasks:

    # upgrade all packages using apt
    - name: upgrade packages
      apt:
        name: '*'
        state: latest
        update_cache: yes

    # check if a reboot is required
    - name: check if reboot is needed
      stat:
        path: /var/run/reboot-required
        get_md5: no
      register: reboot_required

    # show a message f a reboot is needed
    - name: reboot needed message
      debug:
        msg: reboot needed
      when: reboot_required.stat.exists
      
    # do the reboot
    - name: reboot system
      reboot:
        msg: reboot required
        connect_timeout: 5
        reboot_timeout: 300
      when: 1==0
