# check if a reboot is required
- name: check if reboot is needed
  stat:
    path: /var/run/reboot-required
  register: reboot_required
    
# show a message f a reboot is needed
- name: reboot needed message
  debug:
    msg: reboot needed
  when: reboot_required.stat.exists
    
# do the reboot
- name: reboot system
  reboot:
    msg: reboot required
    connect_timeout: 5
    reboot_timeout: 300
  when: allowReboot and reboot_required.stat.exists
    
